repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^mkdocs\.yml$
      - id: check-toml
      - id: check-json
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        files: ^(src|tests)/
      - id: ruff-format
        files: ^(src|tests)/
  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.31.7
    hooks:
      - id: basedpyright
        files: ^(src|tests)/
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uv run ty check . --ignore unresolved-import
        language: python
